dataUserStore:
  type: 'db'
  fileName: '/UserService/user.db'
  echo: True

dataEventStore:
  type: 'db'
  fileName: '/EventService/event.db'
  echo: True

# Microservices dependancies
publicapi:
  host: 'localhost'
  port: 5000
  debug: True
  environment: 'development'

userservice:
  host: 'localhost'
  port: 5001
  debug: True
  environment: 'development'

eventservice:
  host: 'localhost'
  port: 5002
  debug: True
  environment: 'development'

logLevel:
  level: 'INFO'
  fileName: 'execution.log'
